# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JQ2ihwVmjq9dkUrLBfVQrv7l6ruC7ug-
"""

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# Load saved model
model = load_model("/content/deepfake_detector.keras")

# Path of image to test
img_path = "/content/image.jpeg"

# Load and display image
img = image.load_img(img_path, target_size=(224, 224))

plt.imshow(img)
plt.axis("off")
plt.show()

# Convert image to array
img_array = image.img_to_array(img)

# Normalize image
img_array = img_array / 255.0

# Add batch dimension
img_array = np.expand_dims(img_array, axis=0)

# Predict
prediction = model.predict(img_array)

# Print raw prediction value
print("Prediction Score:", prediction[0][0])

# Final result
if prediction[0][0] > 0.5:
    print("Real Image")
else:
    print("Fake Image")